# To load the model for Testing the ML model and to use in GUI App

In [96]:
import pickle as pkl

In [97]:
file = open('model.pkl','rb')
model = pkl.load(file)
file.close()

In [98]:
file = open('gender_label.pkl','rb')
gender_label = pkl.load(file)
file.close()

file = open('gender_onehot.pkl','rb')
gender_onehot = pkl.load(file)
file.close()

file = open('severity_label.pkl','rb')
severity_label = pkl.load(file)
file.close()

file = open('severity_onehot.pkl','rb')
severity_onehot = pkl.load(file)
file.close()

file = open('contact_label.pkl','rb')
contact_label = pkl.load(file)
file.close()

file = open('contact_onehot.pkl','rb')
contact_onehot = pkl.load(file)
file.close()

file = open('minmax.pkl','rb')
minmax = pkl.load(file)
file.close()

In [99]:
age = 50
gender = 'Male'
fever = 99
bodypain = 1
runny_nose = 0
diff = 0
nasal = 1
sore_throat = 0
severity = 'Mild'
contact = 'no'

In [100]:
gender = gender_onehot.transform([gender_label.transform([gender])]).toarray()

In [101]:
severity = severity_onehot.transform([severity_label.fit_transform([severity])]).toarray()

In [102]:
contact = contact_onehot.transform([contact_label.fit_transform([contact])]).toarray()

In [103]:
gender

array([[0., 1., 0.]])

In [104]:
severity

array([[1., 0., 0.]])

In [105]:
contact

array([[1., 0., 0.]])

In [106]:
import numpy as np

In [108]:
test_data = np.array([[age,fever,bodypain,runny_nose,diff,nasal,sore_throat]])

In [109]:
test_X = np.c_[test_data,gender,severity,contact]

In [110]:
test_X

array([[50., 99.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
         1.,  0.,  0.]])

In [112]:
test_X = minmax.transform(test_X)

In [113]:
test_X

array([[0.50632911, 0.16666667, 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ]])

In [114]:
model.predict(test_X)

array([0], dtype=int64)